/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_omniruntime_flink_runtime_metrics_OmniLongSizeGauge */

#ifndef _Included_com_huawei_omniruntime_flink_runtime_metrics_OmniLongSizeGauge
#define _Included_com_huawei_omniruntime_flink_runtime_metrics_OmniLongSizeGauge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_omniruntime_flink_runtime_metrics_OmniLongSizeGauge
 * Method:    getNativeSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_omniruntime_flink_runtime_metrics_OmniLongSizeGauge_getNativeSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
