/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_omniruntime_flink_runtime_metrics_groups_OmniOperatorStateMetricGroup */

#ifndef _Included_com_huawei_omniruntime_flink_runtime_metrics_groups_OmniOperatorStateMetricGroup
#define _Included_com_huawei_omniruntime_flink_runtime_metrics_groups_OmniOperatorStateMetricGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_omniruntime_flink_runtime_metrics_groups_OmniOperatorStateMetricGroup
 * Method:    addOperatorStateMetricGroup
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_omniruntime_flink_runtime_metrics_groups_OmniOperatorStateMetricGroup_addOperatorStateMetricGroup
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
