/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_omniruntime_flink_runtime_metrics_groups_OmniTaskExecutorGlobalVectorBatchMetricGroup */

#ifndef _Included_com_huawei_omniruntime_flink_runtime_metrics_groups_OmniTaskExecutorGlobalVectorBatchMetricGroup
#define _Included_com_huawei_omniruntime_flink_runtime_metrics_groups_OmniTaskExecutorGlobalVectorBatchMetricGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_omniruntime_flink_runtime_metrics_groups_OmniTaskExecutorGlobalVectorBatchMetricGroup
 * Method:    addTaskExecutorGlobalVectorBatchMetricGroup
 * Signature: (JJLjava/lang/String;[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_omniruntime_flink_runtime_metrics_groups_OmniTaskExecutorGlobalVectorBatchMetricGroup_addTaskExecutorGlobalVectorBatchMetricGroup
  (JNIEnv *, jclass, jlong, jlong, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
