/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_huawei_omniruntime_flink_runtime_tasks_OmniSourceStreamTaskV2 */

#ifndef _Included_com_huawei_omniruntime_flink_runtime_tasks_OmniSourceStreamTaskV2
#define _Included_com_huawei_omniruntime_flink_runtime_tasks_OmniSourceStreamTaskV2
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_omniruntime_flink_runtime_tasks_OmniSourceStreamTaskV2
 * Method:    runStreamSource
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_omniruntime_flink_runtime_tasks_OmniSourceStreamTaskV2_runStreamSource
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_huawei_omniruntime_flink_runtime_tasks_OmniSourceStreamTaskV2
 * Method:    cancelStreamSource
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_omniruntime_flink_runtime_tasks_OmniSourceStreamTaskV2_cancelStreamSource
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_huawei_omniruntime_flink_runtime_tasks_OmniSourceStreamTaskV2
 * Method:    resetOutputBufferAndRecordWriter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_huawei_omniruntime_flink_runtime_tasks_OmniSourceStreamTaskV2_resetOutputBufferAndRecordWriter
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
