/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper */

#ifndef _Included_com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper
#define _Included_com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper
 * Method:    createNativeSimpleCounter
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper_createNativeSimpleCounter
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper
 * Method:    createNativeTimeGauge
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper_createNativeTimeGauge
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper
 * Method:    createNativeSizeGauge
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper_createNativeSizeGauge
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper
 * Method:    createNativeOmniDescriptiveStatisticsHistogram
 * Signature: (JILjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_omniruntime_flink_runtime_metrics_utils_OmniMetricHelper_createNativeOmniDescriptiveStatisticsHistogram
  (JNIEnv *, jclass, jlong, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
