/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader */

#ifndef _Included_org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader
#define _Included_org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader
 * Method:    getAvailabilityAndBacklog
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader_getAvailabilityAndBacklog
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader
 * Method:    getNextBuffer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader_getNextBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader
 * Method:    createNativeCreditBasedSequenceNumberingViewReader
 * Signature: (JJLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader_createNativeCreditBasedSequenceNumberingViewReader
  (JNIEnv *, jobject, jlong, jlong, jstring, jint);

/*
 * Class:     org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader
 * Method:    firstDataAvailableNotification
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader_firstDataAvailableNotification
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader
 * Method:    destroyNativeNettyBufferPool
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader_destroyNativeNettyBufferPool
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader
 * Method:    resumeConsumption
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_org_apache_flink_runtime_io_network_netty_OmniCreditBasedSequenceNumberingViewReader_resumeConsumption
  (JNIEnv* jniEnv, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
