/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_flink_metrics_SimpleCounter */

#ifndef _Included_org_apache_flink_metrics_SimpleCounter
#define _Included_org_apache_flink_metrics_SimpleCounter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_flink_metrics_SimpleCounter
 * Method:    getNativeCounterNew
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_flink_metrics_SimpleCounter_getNativeCounterNew
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif