/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class org_apache_flink_runtime_taskexecutor_TaskManagerRunner */

#ifndef _Included_org_apache_flink_runtime_taskexecutor_TaskManagerRunner
#define _Included_org_apache_flink_runtime_taskexecutor_TaskManagerRunner
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_flink_runtime_taskexecutor_TaskManagerRunner_FAILURE_EXIT_CODE
#define org_apache_flink_runtime_taskexecutor_TaskManagerRunner_FAILURE_EXIT_CODE 1L
#undef org_apache_flink_runtime_taskexecutor_TaskManagerRunner_FATAL_ERROR_SHUTDOWN_TIMEOUT_MS
#define org_apache_flink_runtime_taskexecutor_TaskManagerRunner_FATAL_ERROR_SHUTDOWN_TIMEOUT_MS 10000LL
#undef org_apache_flink_runtime_taskexecutor_TaskManagerRunner_SUCCESS_EXIT_CODE
#define org_apache_flink_runtime_taskexecutor_TaskManagerRunner_SUCCESS_EXIT_CODE 0L
/*
 * Class:     org_apache_flink_runtime_taskexecutor_TaskManagerRunner
 * Method:    initTMConfiguration
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_runtime_taskexecutor_TaskManagerRunner_initTMConfiguration
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
