/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel */

#ifndef _Included_org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel
#define _Included_org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel
 * Method:    doChangeNativeLocalInputChannel
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel_doChangeNativeLocalInputChannel
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel
 * Method:    sendMemorySegmentToNative
 * Signature: (JJIIIII)V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel_sendMemorySegmentToNative
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel
 * Method:    getRecycleBufferAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel_getRecycleBufferAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel
 * Method:    registerJavaOmniLocalInputChannel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_org_apache_flink_runtime_io_network_partition_consumer_OmniLocalInputChannel_registerJavaOmniLocalInputChannel
  (JNIEnv *env, jobject, jlong);
#ifdef __cplusplus
}
#endif
#endif
