/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_flink_ReplaceHelper */

#ifndef _Included_org_apache_flink_ReplaceHelper
#define _Included_org_apache_flink_ReplaceHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_flink_ReplaceHelper
 * Method:    nativeReplaceAll
 * Signature: ([CBJ)I
 */
JNIEXPORT jint JNICALL Java_org_apache_flink_ReplaceHelper_nativeReplaceAll
        (JNIEnv *, jclass, jcharArray, jbyte, jlong);

/*
 * Class:     org_apache_flink_ReplaceHelper
 * Method:    nativeReplaceAllGeneric
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_flink_ReplaceHelper_nativeReplaceAllGeneric
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
