/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_flink_Crc32Helper */

#ifndef _Included_org_apache_flink_Crc32Helper
#define _Included_org_apache_flink_Crc32Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_flink_Crc32Helper
 * Method:    nativeCrc32
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_apache_flink_Crc32Helper_nativeCrc32
        (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
