/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_flink_LowerCaseHelper */

#ifndef _Included_org_apache_flink_LowerCaseHelper
#define _Included_org_apache_flink_LowerCaseHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_flink_LowerCaseHelper
 * Method:    nativeLower
 * Signature: ([BB)V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_LowerCaseHelper_nativeLower
        (JNIEnv *, jclass, jcharArray, jbyte);

#ifdef __cplusplus
}
#endif
#endif
